fix: added the ability to create a URL with a parameter
lee-to/laravel-seo-by-url pull request #14
Opened 2024-12-02 09:57 UTC by saydum

2024-12-05 09:08 UTC, DissNik commented
Иде отличная, реализация не совсем удачная, нужно подумать еще.

Вы жестко привязали сео к урл с параметрами и придется прописывать абсолютно все пути со всеми возможными параметрами.

Например я бы хотел прописать сео для `/`  и например для какого-то одного случая `/?page=1`, если стараница `/?page=2` то логично должно работать сео от `/`, но у вас для `/?page=2` вообще ничего не сработает, таким образом все страницы с параметрами вылетят.

2024-12-12 04:39 UTC, DissNik requested changes

2024-12-12 04:39 UTC, DissNik commented on src/SeoManager.php
> +        $baseUrl = parse_url($url, PHP_URL_HOST);
Вам нужен PHP_URL_PATH

$url у вас это `request()->getRequestUri()` где только path и query, `значение` PHP_URL_HOST = null

2024-12-30 17:42 UTC, lee-to commented on src/SeoManager.php
> +        if ($seo) return $seo;
давай заменим на 

```php
if ($seo) {
   return $seo;
}
```

и ниже тоже, всегда используем фигурные

2024-12-31 00:20 UTC, DissNik approved these changes

2024-12-31 00:20 UTC, DissNik commented on src/SeoManager.php
> +        if ($seo) return $seo;
```php
if ($seo) {
    return $seo;
}
```

2024-12-31 00:20 UTC, DissNik commented on src/SeoManager.php
> +        if ($seo) return $seo;
Желательно не использовать стиль без усов

2024-12-31 06:33 UTC, merged